In [3]:
import numpy as np

print("--- Matrix Operations in Neural Networks ---")
print("\nNeural networks heavily rely on matrix operations for processing data,")
print("applying weights, and calculating outputs. NumPy is the go-to library")
print("in Python for efficient array and matrix computations.\n")


--- Matrix Operations in Neural Networks ---

Neural networks heavily rely on matrix operations for processing data,
applying weights, and calculating outputs. NumPy is the go-to library
in Python for efficient array and matrix computations.



In [4]:
# Input data, weights, biases, and activations as matrices
input_features = np.array([[1.0, 0.5, 2.0]])
weights_input_hidden = np.array([
    [0.1, 0.3],
    [0.2, 0.4],
    [0.5, 0.6]
])
biases_hidden = np.array([[0.1, -0.2]])

print("--- Block 1: Representing Data and Weights as Matrices ---")
print(f"Input Features (X) - Shape: {input_features.shape}\n{input_features}\n")
print(f"Weights (W) - Shape: {weights_input_hidden.shape}\n{weights_input_hidden}\n")
print(f"Biases (b) - Shape: {biases_hidden.shape}\n{biases_hidden}\n")


--- Block 1: Representing Data and Weights as Matrices ---
Input Features (X) - Shape: (1, 3)
[[1.  0.5 2. ]]

Weights (W) - Shape: (3, 2)
[[0.1 0.3]
 [0.2 0.4]
 [0.5 0.6]]

Biases (b) - Shape: (1, 2)
[[ 0.1 -0.2]]



In [5]:
net_input_hidden = np.dot(input_features, weights_input_hidden)

print("\n--- Block 2: Matrix Multiplication (Dot Product) ---")
print(f"Net Input to Hidden Layer (X @ W) - Shape: {net_input_hidden.shape}\n{net_input_hidden}\n")



--- Block 2: Matrix Multiplication (Dot Product) ---
Net Input to Hidden Layer (X @ W) - Shape: (1, 2)
[[1.2 1.7]]



In [6]:
activated_hidden_before_activation = net_input_hidden + biases_hidden

print("\n--- Block 3: Matrix Addition (for Biases) ---")
print(f"Net Input + Biases (X @ W + b) - Shape: {activated_hidden_before_activation.shape}\n{activated_hidden_before_activation}\n")



--- Block 3: Matrix Addition (for Biases) ---
Net Input + Biases (X @ W + b) - Shape: (1, 2)
[[1.3 1.5]]



In [7]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

activated_hidden = sigmoid(activated_hidden_before_activation)

print("\n--- Block 4: Element-wise Operations (Activation Functions) ---")
print(f"Activated Hidden Layer (sigmoid(X @ W + b)) - Shape: {activated_hidden.shape}\n{activated_hidden}\n")



--- Block 4: Element-wise Operations (Activation Functions) ---
Activated Hidden Layer (sigmoid(X @ W + b)) - Shape: (1, 2)
[[0.78583498 0.81757448]]



In [8]:
weights_transposed = weights_input_hidden.T

print("\n--- Block 5: Transposition ---")
print(f"Transposed Weights (W.T) - Shape: {weights_transposed.shape}\n{weights_transposed}\n")



--- Block 5: Transposition ---
Transposed Weights (W.T) - Shape: (2, 3)
[[0.1 0.2 0.5]
 [0.3 0.4 0.6]]



In [9]:
batch_input_features = np.array([
    [1.0, 0.5, 2.0],
    [0.2, 1.8, 0.7],
    [1.5, 0.3, 0.9]
])

batch_net_input_hidden = np.dot(batch_input_features, weights_input_hidden)
batch_activated_hidden_before_activation = batch_net_input_hidden + biases_hidden
batch_activated_hidden = sigmoid(batch_activated_hidden_before_activation)

print("\n--- Block 6: Batched Operations ---")
print(f"Batch Input Features (X_batch) - Shape: {batch_input_features.shape}\n{batch_input_features}\n")
print(f"Batch Net Input (X_batch @ W) - Shape: {batch_net_input_hidden.shape}\n{batch_net_input_hidden}\n")
print(f"Batch Activated Hidden Layer - Shape: {batch_activated_hidden.shape}\n{batch_activated_hidden}\n")



--- Block 6: Batched Operations ---
Batch Input Features (X_batch) - Shape: (3, 3)
[[1.  0.5 2. ]
 [0.2 1.8 0.7]
 [1.5 0.3 0.9]]

Batch Net Input (X_batch @ W) - Shape: (3, 2)
[[1.2  1.7 ]
 [0.73 1.2 ]
 [0.66 1.11]]

Batch Activated Hidden Layer - Shape: (3, 2)
[[0.78583498 0.81757448]
 [0.69635493 0.73105858]
 [0.68135373 0.71300016]]



In [10]:
vector_a = np.array([1, 2, 3])
vector_b = np.array([4, 5])
outer_product_matrix = np.outer(vector_a, vector_b)

print("\n--- Block 7: Outer Product ---")
print(f"Vector A: {vector_a}")
print(f"Vector B: {vector_b}")
print(f"Outer Product Matrix (A ⊗ B) - Shape: {outer_product_matrix.shape}\n{outer_product_matrix}\n")
print("--- End of Matrix Operations Explanation ---")



--- Block 7: Outer Product ---
Vector A: [1 2 3]
Vector B: [4 5]
Outer Product Matrix (A ⊗ B) - Shape: (3, 2)
[[ 4  5]
 [ 8 10]
 [12 15]]

--- End of Matrix Operations Explanation ---


In [11]:
import numpy as np
import time

print("--- Matrix Multiplication with Loops ---")

# Create two random 100x100 matrices
A = np.random.rand(100, 100)
B = np.random.rand(100, 100)

# Prepare empty result matrix
C = [[0 for _ in range(100)] for _ in range(100)]

start_time = time.time()

# Triple nested loop (definition of matrix multiplication)
for i in range(100):
    for j in range(100):
        for k in range(100):
            C[i][j] += A[i][k] * B[k][j]

end_time = time.time()

print("Result Shape: (100, 100)")
print("Time taken (Loops):", round(end_time - start_time, 4), "seconds")


--- Matrix Multiplication with Loops ---
Result Shape: (100, 100)
Time taken (Loops): 0.5824 seconds


In [12]:
import torch
import time

print("\n--- PyTorch Tensor Multiplication ---")

# Create random 1000x1000 tensors
A_t = torch.rand(1000, 1000)
B_t = torch.rand(1000, 1000)

start_time = time.time()
C_t = torch.matmul(A_t, B_t)   # or A_t @ B_t
end_time = time.time()

print("Result Shape:", C_t.shape)
print("Time taken (PyTorch):", round(end_time - start_time, 4), "seconds")



--- PyTorch Tensor Multiplication ---
Result Shape: torch.Size([1000, 1000])
Time taken (PyTorch): 0.0445 seconds
