In [1]:
import numpy as np

# Example 1: Add scalar to array
A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = 10   # scalar
print("Example 1: A + B\n", A + B, "\n")

# Example 2: Add row vector to matrix
A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([10, 20, 30])  # row vector
print("Example 2: A + B (row broadcasting)\n", A + B, "\n")

# Example 3: Add column vector to matrix
A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([[10],
              [20]])   # column vector
print("Example 3: A + B (column broadcasting)\n", A + B, "\n")

# Example 4: 1D and 2D broadcast
A = np.ones((3, 1))   # shape (3,1)
B = np.arange(3)      # shape (3,)
print("Example 4: Shapes:", A.shape, B.shape)
print("A + B:\n", A + B, "\n")

# Example 5: Multiply with broadcasting
A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([2, 3, 4])  # row vector
print("Example 5: A * B\n", A * B, "\n")


Example 1: A + B
 [[11 12 13]
 [14 15 16]] 

Example 2: A + B (row broadcasting)
 [[11 22 33]
 [14 25 36]] 

Example 3: A + B (column broadcasting)
 [[11 12 13]
 [24 25 26]] 

Example 4: Shapes: (3, 1) (3,)
A + B:
 [[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]] 

Example 5: A * B
 [[ 2  6 12]
 [ 8 15 24]] 



In [4]:
import numpy as np

A = np.array([[1], [2], [3]])  # shape (3,1)
B = np.array([10, 20, 30])     # shape (3,)
C = A + B
print(A.shape, B.shape, C.shape)
print(C)

(3, 1) (3,) (3, 3)
[[11 21 31]
 [12 22 32]
 [13 23 33]]
