In [1]:
import numpy as np
X = np.array([[0,1],[0,0],[1,0],[1,1]])

In [2]:
y = np.array([0,0,0,1])

In [3]:
epochs =10
lr = 0.01
weights = np.zeros(X.shape[1])
bias = 0

In [4]:
def relu(x):
    return 1 if x>=0 else 0

In [5]:
for epoch in range(epochs):
    for xi,target in zip(X,y):
        linear_output = np.dot(xi,weights)+bias
        y_pred = relu(linear_output)

        update = lr * (target - y_pred)
        weights += update * xi
        bias += update
    print("Weights:",weights)
    print("Bias:",bias)    

Weights: [0.01 0.  ]
Bias: 0.0
Weights: [0.01 0.  ]
Bias: -0.01
Weights: [0.01 0.01]
Bias: -0.01
Weights: [0.02 0.01]
Bias: -0.01
Weights: [0.02 0.01]
Bias: -0.019999999999999997
Weights: [0.02 0.02]
Bias: -0.019999999999999997
Weights: [0.02 0.01]
Bias: -0.03
Weights: [0.02 0.01]
Bias: -0.03
Weights: [0.02 0.01]
Bias: -0.03
Weights: [0.02 0.01]
Bias: -0.03


In [6]:
for xi in X:
    print(f"Input: {xi}, Predicted: {relu(np.dot(xi, weights) + bias)}")

Input: [0 1], Predicted: 0
Input: [0 0], Predicted: 0
Input: [1 0], Predicted: 0
Input: [1 1], Predicted: 1


# PERCEPTRON BUILDING FROM SCRATCH USING IRIS DATASET

In [17]:
import pandas as pd
import numpy as np
import numpy as np

class Perceptron(object):

    def __init__(self, eta=0.01, n_iter=10):
        self.eta = eta
        self.n_iter = n_iter
    def weighted_sum(self, X):
        return np.dot(X, self.w_[1:]) + self.w_[0]
    def predict(self, X):
        return np.where(self.weighted_sum(X) >= 0.0, 1, -1)
    def fit(self, X, y):

        # initializing the weights to 0
        self.w_ = np.zeros(1 + X.shape[1])
        self.errors_ = []

        print("Weights:", self.w_)

        # training the model n_iter times
        for _ in range(self.n_iter):
            error = 0

            # loop through each input
            for xi, y in zip(X, y):

                # 1. calculate ŷ (the predicted value)
                y_pred = self.predict(xi)

                # 2. calculate Update
                # update = η * (y - ŷ)
                update = self.eta * (y - y_pred)

                # 3. Update the weights
                # Wi = Wi + Δ(Wi)   where  Δ(Wi) = η * (y - ŷ) = update * Xi
                self.w_[1:] = self.w_[1:] + update * xi
                print("Updated Weights:", self.w_[1:])

                # Update the bias (Xo = 1)
                self.w_[0] = self.w_[0] + update

                # if update != 0, it means that ŷ != y
                error += int(update != 0.0)

            self.errors_.append(error)

        return self

In [18]:
import pandas as pd
from sklearn.utils import shuffle
import numpy as np
from sklearn.model_selection import train_test_split


df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data', header=None)
# Shuffling the data
df = shuffle(df)

df.head()

,0,1,2,3,4
61,5.9,3.0,4.2,1.5,Iris-versicolor
24,4.8,3.4,1.9,0.2,Iris-setosa
36,5.5,3.5,1.3,0.2,Iris-setosa
96,5.7,2.9,4.2,1.3,Iris-versicolor
15,5.7,4.4,1.5,0.4,Iris-setosa


In [19]:
X = df.iloc[:, 0:4].values
y = df.iloc[:, 4].values

print(X[0:5])
print(y[0:5])

[[5.9 3.  4.2 1.5]
 [4.8 3.4 1.9 0.2]
 [5.5 3.5 1.3 0.2]
 [5.7 2.9 4.2 1.3]
 [5.7 4.4 1.5 0.4]]
['Iris-versicolor' 'Iris-setosa' 'Iris-setosa' 'Iris-versicolor'
 'Iris-setosa']


In [20]:
# 75% for train and 25% for test
train_data, test_data, train_labels, test_labels = train_test_split(
                            X, y, test_size=0.25)

# Encoding the labels: 1 for setosa, -1 otherwise
train_labels = np.where(train_labels == 'Iris-setosa', 1, -1)
test_labels = np.where(test_labels == 'Iris-setosa', 1, -1)

print('Train data:', train_data[0:2])
print('Train labels:', train_labels[0:5])

print('Test data:', test_data[0:2])
print('Test labels:', test_labels[0:5])

Train data: [[5.8 2.7 5.1 1.9]
 [7.2 3.2 6.  1.8]]
Train labels: [-1 -1 -1  1  1]
Test data: [[6.2 3.4 5.4 2.3]
 [5.  3.3 1.4 0.2]]
Test labels: [-1  1  1 -1 -1]


In [21]:
perceptron = Perceptron(eta=0.1, n_iter=10)
perceptron.fit(train_data, train_labels)

Weights: [0. 0. 0. 0. 0.]
Updated Weights: [-1.16 -0.54 -1.02 -0.38]
Updated Weights: [-1.16 -0.54 -1.02 -0.38]
Updated Weights: [-1.16 -0.54 -1.02 -0.38]
Updated Weights: [-0.16  0.18 -0.74 -0.34]
Updated Weights: [ 0.86  0.94 -0.42 -0.3 ]
Updated Weights: [ 0.86  0.94 -0.42 -0.3 ]
Updated Weights: [ 0.86  0.94 -0.42 -0.3 ]
Updated Weights: [ 0.86  0.94 -0.42 -0.3 ]
Updated Weights: [-0.58  0.34 -1.58 -0.62]
Updated Weights: [-0.58  0.34 -1.58 -0.62]
Updated Weights: [-0.58  0.34 -1.58 -0.62]
Updated Weights: [-0.58  0.34 -1.58 -0.62]
Updated Weights: [-0.58  0.34 -1.58 -0.62]
Updated Weights: [-0.58  0.34 -1.58 -0.62]
Updated Weights: [-0.58  0.34 -1.58 -0.62]
Updated Weights: [ 0.42  1.04 -1.32 -0.56]
Updated Weights: [ 0.42  1.04 -1.32 -0.56]
Updated Weights: [ 0.42  1.04 -1.32 -0.56]
Updated Weights: [ 0.42  1.04 -1.32 -0.56]
Updated Weights: [ 0.42  1.04 -1.32 -0.56]
Updated Weights: [ 0.42  1.04 -1.32 -0.56]
Updated Weights: [ 0.42  1.04 -1.32 -0.56]
Updated Weights: [ 0.42  1.0

TypeError: 'numpy.int32' object is not iterable

In [22]:
test_preds = perceptron.predict(test_data)
print(test_preds)

[-1  1  1 -1 -1 -1 -1 -1 -1 -1  1 -1  1 -1 -1 -1 -1 -1 -1  1  1 -1 -1 -1
 -1 -1 -1 -1 -1  1 -1  1 -1  1  1  1 -1 -1]


In [27]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(test_preds, test_labels)
print('Accuracy:', round(accuracy, 2) * 100, "%")

Accuracy: 100.0 %
